"use strict";
let car = 'subaru';
let number = 42;
let color = 'blue';
console.log("Test 1: Is car equal to 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Test 2: Is number less than 50? I predict True.");
console.log(number < 50);
console.log("Test 3: Is color not equal to 'red'? I predict True.");
console.log(color != 'red');
console.log("Test 4: Is car not equal to 'toyota'? I predict True.");
console.log(car != 'toyota');
console.log("Test 5: Is number greater than or equal to 40? I predict True.");
console.log(number >= 40);
console.log("Test 6: Is color equal to 'green'? I predict False.");
console.log(color == 'green');
console.log("Test 7: Is car equal to 'subaru'? I predict False.");
console.log(car == 'honda');
console.log("Test 8: Is number less than or equal to 30? I predict False.");
console.log(number <= 30);
console.log("Test 9: Is color not equal to 'blue'? I predict False.");
console.log(color != 'blue');
console.log("Test 10: Is car not equal to 'subaru'? I predict False.");
console.log(car != 'subaru');
